### ISSUE TITLE
Upload to r-type repository?

### ISSUE THREAD

**Issue by pascalgulikers** [sonatype-nexus-community/nexus-repo-github-action#9]
Hello, I'm trying to upload an R package, but I'm not succesful. Is this even supported?

Run sonatype-nexus-community/nexus-repo-github-action@master
  with:
    serverUrl: https://nexus.host/
    username: ***
    password: ***
    format: r
    repository: r-source
    coordinates: groupId=src.contrib artifactId=myproject version=0.0.0.9000
    assets: extension=gz
    filename: myproject_0.0.0.9000.tar.gz

docker run ******** "https://nexus.host/" "***" "***" "r" "r-source" "groupId=src.contrib artifactId=myproject version=0.0.0.9000" "extension=gz" "myproject_0.0.0.9000.tar.gz"

[main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://nexus.host:443: Connection reset
Caught: com.sonatype.nexus.api.exception.RepositoryManagerException: Upload component was unsuccessful
com.sonatype.nexus.api.exception.RepositoryManagerException: Upload component was unsuccessful
	at com.sonatype.nexus.api.zz.fg.a(SourceFile:93)
	at com.sonatype.nexus.api.zz.fg.a(SourceFile:65)
	at com.sonatype.nexus.api.zz.ff.upload(SourceFile:157)
	at com.sonatype.nexus.api.zz.ff.upload(SourceFile:140)
	at com.sonatype.nexus.api.repository.v3.RepositoryManagerV3Client$upload.call(Unknown Source)
	at NexusPublisher.run(NexusPublisher.groovy:64)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(SourceFile:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(SourceFile:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(SourceFile:221)
	at org.apache.http.impl.client.CloseableHttpClient.execute(SourceFile:165)
	at com.sonatype.nexus.api.zz.fg.a(SourceFile:84)
	... 5 more
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
	at org.apache.http.impl.execchain.RetryExec.execute(SourceFile:108)
	at org.apache.http.impl.execchain.RedirectExec.execute(SourceFile:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(SourceFile:185)
	... 9 more
Caused by: java.net.SocketException: Connection reset
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SourceFile:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SourceFile:1[36](https://github.com/my_company/myproject /runs/6832303601?check_suite_focus=true#step:11:38))
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SourceFile:167)
	at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(SourceFile:122)
	at org.apache.http.impl.io.ChunkedOutputStream.write(SourceFile:179)
	at org.apache.http.entity.mime.content.InputStreamBody.writeTo(SourceFile:93)
	at org.apache.http.entity.mime.AbstractMultipartForm.doWriteTo(SourceFile:134)
	at org.apache.http.entity.mime.AbstractMultipartForm.writeTo(SourceFile:157)
	at org.apache.http.entity.mime.MultipartFormEntity.writeTo(SourceFile:113)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(SourceFile:121)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(SourceFile:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(SourceFile:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(SourceFile:2[38](https://github.com/my_company/myproject/runs/6832303601?check_suite_focus=true#step:11:40))
	at org.apache.http.protocol.HttpRequestExecutor.execute(SourceFile:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(SourceFile:2[72](https://github.com/my_company/myproject/runs/6832303601?check_suite_focus=true#step:11:74))
	at org.apache.http.impl.execchain.ProtocolExec.execute(SourceFile:185)
	at org.apache.http.impl.execchain.RetryExec.execute(SourceFile:89)
	... 11 more

**Comment by pascalgulikers** [comment]
It seems that for R repositories, there are no component fields, and only 1 asset field which is pathId
Component fields are required for NexusPublisher.groovy though, so I'm stuck..
